### ISSUE TITLE
Getting error while executing deployment in Cloudify

### ISSUE THREAD

**Issue by vinayakmshinde** [cloudify-incubator/cloudify-terraform-plugin#3]
[root@ScIndia cloudify-terraform-plugin]# cfy executions start install -vv \
>     -d $deploymentid;

Executing workflow `install` on deployment `terraform` [timeout=900 seconds]
2019-01-22 05:39:16.688  CFY <terraform> Starting 'install' workflow execution
2019-01-22 05:39:17.282  CFY <terraform> [aws_two_tier_example_6xldyy] Creating node
2019-01-22 05:39:17.282  CFY <terraform> [aws_two_tier_example_6xldyy.create] Sending task 'cloudify_tf.tasks.init'
2019-01-22 05:39:17.994  CFY <terraform> [aws_two_tier_example_6xldyy.create] Task started 'cloudify_tf.tasks.init'
2019-01-22 05:39:19.394  LOG <terraform> [aws_two_tier_example_6xldyy.create] INFO: Downloaded resources/aws-two-tier.zip to /tmp/6I8DR/aws-two-tier.zip
2019-01-22 05:39:20.129  CFY <terraform> [aws_two_tier_example_6xldyy.create] Task failed 'cloudify_tf.tasks.init' -> /tmp/tmpGbuWHj/main.tf is not a valid directory path.
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 689, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 392, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 413, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/terraform-tf/lib/python2.7/site-packages/cloudify_tf/tasks.py", line 33, in init
    get_terraform_source(resource_config),
  File "/opt/mgmtworker/env/plugins/default_tenant/terraform-tf/lib/python2.7/site-packages/cloudify_tf/utils.py", line 107, in get_terraform_source
    source = unzip_archive(terraform_source_zip)
  File "/opt/mgmtworker/env/plugins/default_tenant/terraform-tf/lib/python2.7/site-packages/cloudify_tf/utils.py", line 83, in unzip_archive
    unzipped_work_directory))
NonRecoverableError: /tmp/tmpGbuWHj/main.tf is not a valid directory path.

2019-01-22 05:39:20.815  CFY <terraform> 'install' workflow execution failed: RuntimeError: Workflow failed: Task failed 'cloudify_tf.tasks.init' -> /tmp/tmpGbuWHj/main.tf is not a valid directory path.
Execution of workflow install for deployment terraform failed. [error=Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 549, in _remote_workflow_child_thread
    workflow_result = self._execute_workflow_function()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 578, in _execute_workflow_function
    result = self.func(*self.args, **self.kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/plugins/workflows.py", line 27, in install
    node_instances=set(ctx.node_instances))
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/plugins/lifecycle.py", line 28, in install_node_instances
    processor.install()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/plugins/lifecycle.py", line 93, in install
    graph_finisher_func=self._finish_install)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/plugins/lifecycle.py", line 114, in _process_node_instances
    self.graph.execute()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/workflows/tasks_graph.py", line 129, in execute
    self._handle_terminated_task(task)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/workflows/tasks_graph.py", line 203, in _handle_terminated_task
    raise RuntimeError(message)
RuntimeError: Workflow failed: Task failed 'cloudify_tf.tasks.init' -> /tmp/tmpGbuWHj/main.tf is not a valid directory path.
]
* Run 'cfy events list -e fb12d430-cf27-4dce-94be-3bc64c0a5542' to retrieve the execution's events/logs
[root@ScIndia cloudify-terraform-plugin]#

**Comment by EarthmanT** [comment]
Hello,
Can you tell me some specs about the VM that your manager is running on? Where did you get the VM? Is it a publicly available image that I can access? Do you have SE Linux enabled?

**Comment by vinayakmshinde** [comment]
Hello Earthman,

Thanks for your reply.

The manager is running on CentOS 7.6.1810 (Core). This is prebuild virtual box image. This image is publicly available. I have installed manager(communiy version) manually through rpm package. The selinux is permissive.
